# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf-deck" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "46f2e39abcb4fe9f41bbd7f4dffc45bfbdbe884c6962e9afb321abe525334a32"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "07b7d0242618411aab82ccef1177ba139d4df6f78a53594c449644fdbe6a3fc3"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e712705d8e67ea9bcc388b3a88b53ddf0ec98542782e26b411b99c2d583d686d"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8526959962413c6c6f3ca0a6fc85d4080d11bea78b8c0aa35d0cf1ccbf17a6c3"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf-deck"
  desc "Keyboard-first Salesforce workspace across multiple orgs"
  homepage "https://github.com/Jacob-Stokes/sf-deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf-deck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sf-deck"] if OS.mac?
  end

  # No zap stanza required

end
