# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf-deck" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "c1fdec974362cc398844d66e91697f1de91a1ed2c24ea291b30d396c42db7bfd"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "545fa906e4017a6d4593451f48c50bc1f8656056795a0b2a2cd5aeb955ab6441"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ade747fb072138df198012135aa9496a30a8d6e5898a1657ca90dcab93593b3"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "efd93e55aa5c1c04d57f011fa7bf98733e80ba854a3ae99d395c760ddca9fefc"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf-deck"
  desc "Keyboard-first Salesforce workspace across multiple orgs"
  homepage "https://github.com/Jacob-Stokes/sf-deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf-deck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sf-deck"] if OS.mac?
  end

  # No zap stanza required

end
