# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf-deck" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "1497992090418e0482db446884d7fa4ae7187e7334561c98d0d6dbf0502ee498"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a2ad26190feb8d6984c676df9ac2a390a5060650a5348ca4053ae10dd54eebb"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57d2f33cff4789b9c57993c762e901e53a105258780c33c0c315020450f42542"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b06ef82fca0760b7390b52564dc3279655f7acd38f3f92baa2cf34b642def478"
      url "https://github.com/Jacob-Stokes/sf-deck/releases/download/v#{version}/sf-deck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf-deck"
  desc "Keyboard-first Salesforce workspace across multiple orgs"
  homepage "https://github.com/Jacob-Stokes/sf-deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf-deck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sf-deck"] if OS.mac?
  end

  # No zap stanza required

end
